spring:
  cloud:
    config:
      server:
        native:
          search-loc
          ations: classpath:/shared    --设置配置文件存放路径
  profiles:
     active: native                    --本地存放配置文件
  application:
    name: config-server
# port
server:
  port: 5010

management:
  security:
    enabled: false