eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
  instance:
      prefer-ip-address: true
server:
  port: 5004
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-b:
      path: /user/**
      serviceId: user


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS